name: choropleth-environment
channels:
  - conda-forge
  - bioconda
  - pyviz
  - ioam
dependencies:
  - python
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - shapely
  - geopandas
  - scipy
  - plotly
  - seaborn
  - cufflinks
  - plotly
  - dash
  - plotnine
  - holoviews
  - geoviews
  - scikit-learn
  - pandas-datareader
  - altair
  - vega_datasets
  - vega
  - notebook
  - pip:
    - plydata
    - scikit-misc
