name: choropleth-environment
channels:
  - conda-forge
  - bioconda
  - pyviz
dependencies:
  - python
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - shapely
  - geopandas
  - scipy
  - plotly
  - seaborn
  - cufflinks
  - plotly
  - dash
  - plotnine
  - holoviews
  - pip:
    - plydata
