name: choropleth-environment
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - shapely
  - geopandas
  - scipy
  - plotly
  - seaborn
  - cufflinks
  - plotly
  - dash
