name: choropleth-environment
channels:
  - conda-forge
dependencies:
  - python3
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - shapely
  - geopandas
  - scipy
